Feature/db middleware
Party-Buddy/backend pull request #15
Opened 2023-11-19 17:02 UTC by AleksandrMatsko

2023-11-19 17:12 UTC, slowlime commented
Была ли какая-то причина, почему юзается не [это](https://github.com/gorilla/mux#middleware)? Оборачивать каждый хэндлер ломает всю суть затеи.

2023-11-19 17:19 UTC, AleksandrMatsko commented
Насколько я понимаю иначе оно применится ко всему Router. (Не думаю, что нам это надо)

2023-11-19 17:24 UTC, AleksandrMatsko commented
Могу попытаться поиграться с Route.Subrouter, но не уверен, что станет лучше, когда появиться второй middleware

2023-11-19 17:27 UTC, slowlime commented
> Насколько я понимаю иначе оно применится ко всему Router. (Не думаю, что нам это надо)

А нам это надо. У нас нет раутов, которые не лезут в БД.

> Могу попытаться поиграться с Route.Subrouter, но не уверен, что станет лучше, когда появиться второй middleware

А в этом нет пока необходимости. (Auth middleware надо будет настэкать после DB middleware аналогичным образом, не предвижу проблем из-за этого.)

2023-11-19 17:47 UTC, AleksandrMatsko commented
Исправлено

2023-11-19 18:31 UTC, slowlime requested changes

2023-11-19 18:31 UTC, slowlime commented on internal/api/handlers/config.go
> +func ConfigureMux(ctx context.Context, pool *db.DBPool) *mux.Router {
Здесь вроде не нужен контекст.

2023-11-19 18:31 UTC, slowlime commented on internal/api/handlers/config.go
> +	r.Handle("/api/v1/images/{img-id}", GetImageHandler{}).Methods(http.MethodGet)
Почему бы не оставить хэндлер функцией?

2023-11-19 18:31 UTC, slowlime commented on internal/api/handlers/image_handlers.go
> +	ctx := r.Context().Value("ctx").(context.Context)
Как я вижу, тут выдёргивается контекст из контекста. Это очень подозрительно. У обработчика должен быть ровно один контекст — его получаем через `r.Context()`, — в котором содержится вся нужная информация. И именно этот контекст надо передавать во все функции.

2023-11-19 18:31 UTC, slowlime commented on internal/api/handlers/image_handlers.go
> +	ctx := r.Context().Value("ctx").(context.Context)
Не надо выдёргивать поля контекста напрямую. Про это ниже.

2023-11-19 18:31 UTC, slowlime commented on internal/api/middleware/middlewares.go
> +		ctx = context.WithValue(ctx, "ctx", dbm.Ctx)
Ключами контекста не должны быть строки. Рекомендую обратиться к документации пакета `context`. Нужно сделать неэкспортируемый тип, неэкспортируемую глобалку с zero value этого типа, и её значение использовать в качестве ключа. Затем создать функцию, которая выдёргивает `pgx.Tx` из контекста.

```go
type txKeyType int
var txKey txKeyType

func TxFromContext(ctx context.Context) pgx.Tx {
    return ctx.Value(txKey).(pgx.Tx)
}
```

В самой миддлвари же просто наращивать контекст:

```go
r.WithContext(r.Context().WithValue(txKey, tx))
```

2023-11-19 18:31 UTC, slowlime commented on internal/api/middleware/middlewares.go
> +			dto := api.Errorf(api.ErrInternal, "failed to start transaction")
Не следует всем встречным говорить о том, что у нас проблемы с БД. Клиенту надо писать только про проблемы клиента. Внутренние проблемы сервера должны идти в логи, но никак не клиенту.

2023-11-19 18:31 UTC, slowlime commented on internal/api/middleware/middlewares.go
> +		_ = tx.Rollback(dbm.Ctx)
Советую использовать `defer`, причём сразу после проверки, что транзакция успешно создалась.

2023-11-19 18:31 UTC, slowlime commented on internal/main.go
> +	ctx = validate.NewContext(ctx, factory)
Фабрику в контекст прописывать тоже должна миддлварь. Отдельная. Не надо рутовый контекст отдавать в обработчики.

2023-11-20 04:08 UTC, slowlime approved these changes

2023-11-20 04:08 UTC, slowlime commented on internal/db/connection_pool.go
> +	ctx  context.Context
Это поле, кажется, нигде не юзается и нигде не сетится.

2023-11-20 04:13 UTC, merged