Feature/11057 rw ws cycle
Party-Buddy/backend pull request #19
Opened 2023-11-21 10:16 UTC by AleksandrMatsko

2023-11-21 13:31 UTC, slowlime requested changes
Пока на этом остановлюсь.

2023-11-21 13:31 UTC, slowlime commented on internal/schemas/schemas.go
> +	PollDuration DurationType `json:"poll-duration,omitempty"`
Имхо, надо либо 4 типа тасок делать отдельными `type`, и тогда никаких `omitempty` быть не должно, либо делать одну структуру сразу на все 4 типа с `omitempty` в полях, не присущим всем типам.

2023-11-21 13:31 UTC, slowlime commented on internal/schemas/ws/ws_schema.go
> +
Там точно нужен атомик для этого? И он точно должен жить в этом модуле? Есть же структура со стейтом соединения: можно сделать там поле `NextMsgID` и юзать его. Айдишники ж уникальными только в пределах соединения должны быть.

2023-11-21 13:31 UTC, slowlime commented on internal/schemas/ws/ws_schema.go
> +
Протокол не позволяет отправлять кому-либо просто `BaseMessage`. Обязательно должны быть дополнительные поля.

2023-11-21 13:31 UTC, slowlime commented on internal/session/event.go
> +	Ctx context.Context
Хотелось бы комментариев, почему оно теперь так.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +			ctx = context.WithValue(ctx, joinKey, *joinMsg.MsgId)
Предлагаю в интерфейс `RecvMessage` добавить `MsgId() MessageId`, и в контекст забивать этот айдишник перед свичом. Ну и, кроме того, `joinKey` к сообщению `Join` отношения не имеет (не должен, по крайней мере).

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +					{
Там раньше были скобки, так же расставленные в ветках `switch/case`, и я тогда это проигнорил, сочтя за единичный случай, но тут он далеко не единичный. Есть какой-то положительный эффект от того, что код сдвигается ещё на 8 символов вправо?

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +								Message: err.Error(),
Ошибки из менеджера могут (то есть обязаны) идти в логи, но никак не клиенту, потому что там могут содержаться внутренние сведения. Надо сообщения составлять здесь самому и вручную.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +				}
Этот код без варёной копипасты получится записать? Для прототипа-то ещё ладно, но эта каша же в каждом методе будет. 3к строк такого видеть не очень хочется.

Код при этом совершенно однотипный, различается только в содержимом `ws.Error`. Может, тогда и вынести это в отдельную переменную, которую в каждой ветке просетить, и уже после свича оформлять сообщение/логировать?

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +				}
Так, а если там какая-то другая ошибка? Внештатная. Надо предусмотреть и выслать `internal`.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +			c.playerID = playerID
Вот это всё надо вынести в отдельный метод.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
>  	_ = c.wsConn.Close()
Сделай типы каналов в структуре однонаправленными. Даже если они двусторонние, в структуре должен лежать только и ровно одно из двух направлений: другое передать параметром горутине, которая будет его обрабатывать.

Потому что из-за этого здесь вот, например, на приёмнике закрывается канал, чего делать в го категорически нельзя. Взлетит на воздух это всё.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +	// TODO: set Time
Это же буквально делается через `time.Now()`.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/converters.go
Предлагаю вынести конвертеры в отдельный подпакет `ws/converters`, и выбрать поприличнее имена методам: мне кажется, `ToPollDuration` достаточно (вообще, ты же в `DurationType` конвертишь, тогда и `ToDurationType` надо писать). Тип, из которого мы конвертим, написан прямо после метода, можно не дублировать.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/converters.go
> +	return schemas.DurationType{}, errors.New("bad poll duration from server")
Думаю, лучше паникнуть. Такая ошибка должна стрелять и очень громко.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/converters.go
> +			sessionPollTask := t.(*session.PhotoTask)
```suggestion
	switch t := t.(type) {
	case *session.PhotoTask:
		{
```

Можно присваивать в type-свиче — слева будет даункасченная переменная. Внизу, вон, как раз ошибка из-за этого.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/converters.go
> +		return &schemas.BaseTask{}, errors.New("bad task from server")
Лучше паниковать: попадание сюда — нарушение инварианта.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/converters.go
Никакая функция-конвертер не должна отдавать ошибку.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +					c.msgToClientChan <- &joinedMsg
А он так не задедлочится?

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +				continue
> Все ошибки являются фатальными. После отправки ошибки отправитель закрывает соединение.

2023-11-21 13:31 UTC, slowlime commented on internal/ws/conn_info.go
> +								Code:    ws.ErrUnknownSession,
Самодеятельность. Такого в апи не предусмотрено. Внимательнее:

> Если сессия недействительна, то сервер отправляет `Error` с кодом ошибки `session-expired`.

2023-11-21 13:34 UTC, AleksandrMatsko commented on internal/session/event.go
> +	Ctx context.Context
У меня начинает путаться между полем Context и функцией Context(). Напоролся, когда хотел реализовать метод Context для MsgJoin

2023-11-21 13:38 UTC, AleksandrMatsko commented on internal/ws/conn_info.go
> +					{
go fmt ./... расставил так...

2023-11-21 13:39 UTC, slowlime commented on internal/session/event.go
> +	Ctx context.Context
Так его не надо реализовывать самому. Оно специально потому и называется так, чтобы автоматически реализовывалось включением базового типа.

2023-11-21 15:58 UTC, AleksandrMatsko commented on internal/session/event.go
> +	Ctx context.Context
Сделал вот так:
![image](https://github.com/Party-Buddy/backend/assets/90016901/dfe0cabc-0aa4-4ce5-9df3-32ed35b538c9)
После go vet ./... получаю:
![image](https://github.com/Party-Buddy/backend/assets/90016901/12c14ae3-1c87-416b-9f39-54a4753caefe)

Попробовал убрать baseTx из MsgJoined:
![image](https://github.com/Party-Buddy/backend/assets/90016901/58854f35-8989-478c-b952-ab0be07d0744)
Получил:
![image](https://github.com/Party-Buddy/backend/assets/90016901/e085f67b-41bf-4c85-9bfa-52939806ca54)

По итогу оставил название поля тем же. Просто сделал метод Context() для baseTx

2023-11-21 16:00 UTC, AleksandrMatsko commented
Спасибо за ревью

2023-11-21 16:09 UTC, slowlime commented on internal/session/event.go
> +	Ctx context.Context
А-а-а-а-а. Что-то я реально тупанул. Короче, ща это сделано ровно так, как я задумывал. Блестяще.

2023-11-21 16:54 UTC, slowlime commented on internal/configuration/config.go
> +	appEnvOuterPrefix = "PARTY_BUDDY_OUTER"
Лучше либо `PUBLIC`, либо `EXTERNAL`. Слово `OUTER` как-то ввело в ступор.

2023-11-21 16:54 UTC, slowlime commented on internal/schemas/schemas.go
> +}
Интерфейс не нужен, если конкретный тип всего один.

2023-11-21 16:54 UTC, slowlime commented on internal/schemas/schemas.go
> +type DurationKindType string
А зачем приписка `Type` к типу? Есть какой-то другой `DurationKind`?

2023-11-21 16:54 UTC, slowlime commented on internal/schemas/schemas.go
> +type DurationType struct {
Ну и тут тип `DurationType`. Венгерская нотация какая-то, как ещё деды в ассемблерах этих делали. По протоколу-то тип вообще `PollDuration` называется, так пусть и здесь это же имя носит. Удобнее же будет только, когда апи на код прямо кладётся.

2023-11-21 16:54 UTC, slowlime commented on internal/schemas/ws/ws_schema.go
>  }
Лучше б это в `BaseMessage` вынести. Чтоб на все сообщения сразу было. Не знаю, правда, как поле там назвать, чтоб не было конфликта.

(Я ещё почему-то в коде везде пишу `Id` вместо `ID`, хотя в го так не принято. Поправлю потом.)

2023-11-21 16:54 UTC, slowlime commented on internal/ws/converters/join_converters.go
Хм, а это на каждое сообщение свои конвертеры в своих файлах будут, получается? Судя по имени, как минимум, такое впечатление складывается.

2023-11-21 16:54 UTC, slowlime commented on internal/ws/handle_msgs.go
> +		errMsg.MsgId = &id
Я вообще думал, что эти айдишники ты прямо в методы создания протокольных сообщений будешь передавать. Но раз так не делаешь, лучше тогда присваивание (и выделение ид) делать в писателе в сокет, а не каждый раз на каждое сообщение, как здесь.

2023-11-21 17:00 UTC, slowlime commented on internal/ws/conn_info.go
> +					{
Какой-то неправильный фмт. У меня он так не расставляет. Ну ок.

2023-11-21 17:16 UTC, AleksandrMatsko commented on internal/ws/converters/join_converters.go
получается... Ну мб потом все сольём в один, но пока, чтобы не было слишком много кода в одном месте разделил.

2023-11-21 17:17 UTC, slowlime commented on internal/ws/converters/join_converters.go
Ну, да, имена файла не железобетонно забиваются, потом всегда можно перетаскать, поэтому ок.

2023-11-21 19:34 UTC, slowlime approved these changes
Блин, почти! Всё остальное-то вроде норм. Поправить — и можно мёржить.

2023-11-21 19:34 UTC, slowlime commented on internal/configuration/config.go
> +	_ = viper.BindEnv("outer.port", appEnvExternalPrefix+"_PORT")
Блин, но в конфиге-то осталось....

2023-11-21 19:34 UTC, slowlime commented on internal/ws/conn_info.go
> +	servDataChan chan<- session.ServerTx
Не в ту сторону канал. Поэтому с `close` проблема всё ещё не исправлена.

2023-11-22 02:11 UTC, AleksandrMatsko commented
Исправлено. Если остальное ок, то мёрджи. И получается я двину таски:
- цикл чтения сообщений ...
- определение типов сообщений ...
в **Resolved**?

2023-11-22 04:08 UTC, slowlime commented
> Исправлено. Если остальное ок, то мёрджи. И получается я двину таски:
> 
>     * цикл чтения сообщений ...
> 
>     * определение типов сообщений ...
> 
> 
> в **Resolved**?

Ага. Всё добротно сделано.

2023-11-22 04:08 UTC, merged