Add Docker files
Party-Buddy/backend pull request #20
Opened 2023-11-21 15:55 UTC by slowlime

Собственно, вот:

1. два докер файла: на бэк и на бд
2. прогон миграций
3. компост.йамл

2023-11-21 16:50 UTC, AleksandrMatsko requested changes

2023-11-21 16:50 UTC, AleksandrMatsko commented on README.md
> +$ echo "my-pg-password" | podman secret create postgres-passwd
С первого раза с docker не завелось. Пришлось создать файл, в него записать пароль. И отдать его команде docker secret create postgres-passwd my_file

2023-11-21 16:50 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
Опять же с docker получаю ошибку: unsupported external secret postgres-passwd. В процессе поиска решений и причин возникновения.

2023-11-21 16:50 UTC, AleksandrMatsko commented on Makefile
Думаю настало время для решения TODO в этом файле, по созданию таргета для compose

2023-11-21 16:58 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
Завелось чутка вот-так: `docker stack deploy --compose-file compose.yaml party-buddy`. Но теперь ошибка: `services.backend.depends_on must be a list`

2023-11-21 17:00 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
Попытка поменять значение `depends_on` на 
```
depends_on:
  - postgres
```

Привела к: `(root) Additional property name is not allowed`

2023-11-21 17:04 UTC, slowlime commented on README.md
> +$ podman compose -f compose.yaml up
Ясно, там в докере нужна какая-то муть со swarm, чтоб секреты так работали. (Поэтому докер не юзаю...) Буду фиксить.

2023-11-21 17:07 UTC, slowlime commented on README.md
> +$ podman compose -f compose.yaml up
> Но теперь ошибка: `services.backend.depends_on must be a list`

Чего-то я не понимаю в этой жизни. 
![image](https://github.com/Party-Buddy/backend/assets/90332124/6f969d81-b5b5-4953-9d19-344041ccb17b)

Буквально по спеке сделал же..... Может, докер древний?

2023-11-21 17:11 UTC, slowlime commented on README.md
> +$ echo "my-pg-password" | podman secret create postgres-passwd
Ща подниму докер, ладно.... Посмотрим, что происходит.

2023-11-21 17:20 UTC, slowlime commented on Makefile
А что он должен делать? Одну команду исполнить? `up`/`start`? Стопать тоже надо?

2023-11-21 17:32 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
хз

2023-11-21 17:35 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
Прочекал.
- docker: 24.0.6
- docker compose: 2.23

2023-11-21 17:35 UTC, AleksandrMatsko commented on Makefile
я бы предложил, чтобы она поднимала, но было бы неплохо, если будет команда и для остановки

2023-11-21 17:38 UTC, AleksandrMatsko commented on README.md
> +$ podman compose -f compose.yaml up
Мб поменять `.yaml` на `.yml` ? Правда вряд ли поможет...

2023-11-21 18:04 UTC, AleksandrMatsko commented
Предлагаю так: завтра я пробую podman. Если у тебя получится с docker, то ок. Если нет, то надо будет вынести вопрос на обсуждение...

2023-11-21 19:25 UTC, slowlime commented on README.md
> +$ echo "my-pg-password" | podman secret create postgres-passwd
Секреты теперь в `./container/postgres-passwd.txt`. Работает как часы как в podman, так и в docker.

2023-11-21 19:27 UTC, slowlime commented on README.md
> +$ podman compose -f compose.yaml up
`.yml` не канон:

![image](https://github.com/Party-Buddy/backend/assets/90332124/d63c1dc2-91c5-401c-8df0-8745efb2d7f8)

Остальное должно уйти с последним коммитом. Ну, у меня всё работает (докер 24.0.7), а так как это контейнеры, то работать должно у всех.

2023-11-21 19:28 UTC, slowlime commented on Makefile
Ну, короче, после приёмо-сдаточных испытаний выяснилось, что там остановка через ^C, поэтому рецепт будет бесполезен.

2023-11-22 03:07 UTC, AleksandrMatsko approved these changes

2023-11-22 03:11 UTC, merged