Feature/create session endpoint
Party-Buddy/backend pull request #25
Opened 2023-11-24 18:30 UTC by AleksandrMatsko

Итак. Дописал эндпоинты до более менее рабочего состояния. Пока вижу, что у нас возникнет множество проблем с кастомными ошибками.

2023-11-25 21:58 UTC, slowlime requested changes
Сорри, что так поздно ревью пишу ща. СПД......................................

В целом, выглядит достойно. С ошибками надо немного разобраться: я там в комментах предлагаю вариант через `As`. Думаю, стоит попробовать.

2023-11-25 21:58 UTC, slowlime commented on internal/api/handlers/entity_to_session.go
> +		return session.Game{}, api.Errorf(api.ErrNotFound, err.Error())
Опасно так делать. Это же формат-функция. Хотя бы `"%s"` лучше... (В других местах тоже.)

Ну и привычное уже: сообщение это показывается пользователю. Не надо показывать пользователю кишки ошибок базы данных. Это надо в лог.

Если хотим сохранить ошибку (потому что в этой функции логировать реально странно), надо брать не `api.Errorf`, а что-то другое. Я б сделал отдельный тип, которому б ещё `As` реализовал, чтобы он user-facing ошибку `*api.Error` форматировал. Типа у нас весь контекст останется, и в обработчике мы сможем в лог напечатать полезную нам ошибку, но при этом юзеру пошлём то, что через `errors.As` получим.

2023-11-25 21:58 UTC, slowlime commented on internal/api/handlers/session.go
> +		}
Хм, может, тогда в `api.Error` добавить поле (с `json:"-"`) со статус-кодом? А то ведь действительно сдохнем от таких свичкейсов в каждом хендлере...

2023-11-25 21:58 UTC, slowlime commented on internal/api/handlers/session.go
> +		log.Printf("request: %v %v -> err: %v", r.Method, r.URL.String(), dto.Error())
Здесь стоит печатать не `dto.Error()`, а исходный `err`.

Кстати, мне казалось, `.String()` и `.Error()` необязательно писать в форматирующих функциях (если `%s` указывать). Я ошибаюсь?

2023-11-25 21:58 UTC, slowlime commented on internal/api/handlers/session.go
> +	defer tx.Commit(r.Context())
Предлагаю коммитить сразу :slightly_smiling_face:

2023-11-25 21:58 UTC, slowlime commented on internal/api/middleware/auth.go
> +			dto := api.Errorf(api.ErrInternal, "internal server error while getting user")
Не стоит столь подробно писать, когда ошибка у нас.

Вообще, я в каждом PR говорю одно и то же. Давай проясню, по какой логике придираюсь к сообщениям об ошибке. Представь, что на наш апи хакер пробирается. Вот он написал SQL-инъекцию и видит `internal server error while getting user`. Буквально пальцем ему тычут хакать серв через заголовок. А мы не хотим этого.

Поэтому юзеру надо отдавать только безопасное и только то, **на что он сам может повлиять**. На ошибку чтения БД он не может повлиять (ну, в нормальной работе, не должен :slightly_smiling_face:). А вот `internal server error` ему достаточно: клиент понял, что дурак не он.

При валидации же мы клиенту пишем прямо путь к полю, где косяк: ведь его как раз клиент и составляет.

Однако это не означает, что мы должны отбрасывать ценную инфу об ошибке. Вдруг баг у нас? `internal server error` нам не о многом расскажет: поэтому исходную ошибку, до превращения в `api.Error`, логируем. (Это я просто говорю, чтоб закончить на чём-то, потому что у тебя с этим всё очень круто: логи есть на каждую точку выхода.)

2023-11-25 21:58 UTC, slowlime commented on internal/configuration/constants.go
> +	PlayerMax int8 = 20
Думаю, константы эти можно без типа оставить, удобнее будет. Или оно где-то нужно?

2023-11-25 21:58 UTC, slowlime commented on internal/db/games.go
> +	}
Я ща совсем к фигне прикопаюсь: идшки же — primary key, они не могут повторяться. Можно там метод заюзать для выборки одной строки.

2023-11-25 21:58 UTC, slowlime commented on internal/util/validation.go
> +}
Думаю, этим лучше заниматься клиенту. На сервере это будет неуклюже выглядеть, плюс люди с фронта могут десинк стейта словить неожиданный. Предлагаю Ё/ё убрать из списка допустимых символов на сервере.

2023-11-25 21:58 UTC, slowlime commented on internal/schemas/resp_schemas.go
>  }
Заверни в `api/` лучше. В протоколе мы вроде такие сущности не юзаем.

2023-11-25 21:58 UTC, slowlime commented on internal/schemas/recv_schemas.go
> +	checkedTextReg := regexp.MustCompile(fmt.Sprintf("[%v]", configuration.CheckedTextAnswerTemplate))
Не, давай лучше в глобалку регекс вынесем. Вместо того, чтобы список символов хранить. Оно и футган (символ `-` в строке может сломать всё незаметно для нас), и эффективнее станет (он на регекс автомат строит с сотней узлов).

(В этом смысле хорошо, что в го нужно явно компилировать регексы и простых матчей нету.)

2023-11-25 21:58 UTC, slowlime commented on internal/schemas/recv_schemas.go
> +			Not().Blank().InSlice([]GameType{Public, Private}, "game-type"))
Помнишь, я закидывал отдельным PR док-коммент с описанием того, как надо поля в получаемых структурах валидировать? Вот я там писал, что все поля должны быть ссылками, которые надо чекать, иначе ты никак не узнаешь, что поля юзер вообще не давал. А это очень сильно может голову сломать юзеру апи (нашим бедным фронтэндерам).

Прошу перечитать коммент и переделать соответственно во всех `Validate`.

2023-11-25 21:58 UTC, slowlime commented on internal/session/manager.go
> +		},
О, хорошо, что заметили. Давай тогда в функцию вынесем создание `UnsafeStorage` (`NewUnsafeStorage`)? Ну и синхрохран аналогично.

2023-11-25 21:58 UTC, slowlime commented on internal/session/manager.go
> +			return fmt.Errorf("could not register an image (id %s) for session %s: %w", imageId, sid.UUID().String(), err)
Было б неплохо прикрутить `Stringer` к айдишникам. Писать эти вызовы — пальцы в отбивную превратятся.

2023-11-26 07:37 UTC, AleksandrMatsko commented on internal/configuration/constants.go
> +	PlayerMax int8 = 20
в документации к протоколу есть

2023-11-26 08:28 UTC, AleksandrMatsko commented on internal/db/games.go
> +	}
кажется там нет адекватного метода, который бы смог одну строку перегнать в нужную структуру...

2023-11-26 11:06 UTC, slowlime commented on internal/db/games.go
> +	}
Вроде `CollectOneRow` — оно.

2023-11-26 11:08 UTC, slowlime commented on internal/configuration/constants.go
> +	PlayerMax int8 = 20
А, вон что. Ну у нас внутри типы совпадать необязательно должны, вообще говоря, особенно для таких констант, которые на провод никогда не пишутся.

2023-11-26 11:28 UTC, slowlime approved these changes
Я так понял, идея с `As` тебе не зашла. Ну, в целом, если тебе будет проще так, то и ладно.

Хотел бы ещё отметить, что из-за `Passing()` сообщения от валидатора будут бесполезными (она скажет: "вот тут у вас ошибка", — а какая?). В будущем надо это учитывать.

2023-11-26 11:28 UTC, slowlime commented on internal/schemas/api/api_schema.go
> +func (e Error) String() string {
Если ты хочешь, чтоб тут не было ссылок, тогда и `Errorf` скажи без ссылки отдавать.

2023-11-26 17:09 UTC, merged