Feature/11165 task start end
Party-Buddy/backend pull request #29
Opened 2023-11-29 10:55 UTC by AleksandrMatsko

Сделал старт и завершение задания. Но для полного счастья надо сделать `scoreboard` и реализовать функцию `makeMsgTaskEnd`

2023-11-29 11:40 UTC, slowlime requested changes

2023-11-29 11:40 UTC, slowlime commented on internal/session/event.go
> +func (*CheckedTextEventAnswer) isEventAnswer() {}
Лучше отослать экземпляр `Task` здесь. Это ведь всё ещё сущность пакета сессии.

2023-11-29 11:40 UTC, slowlime commented on internal/session/event.go
> +	// TODO: scoreboard
Думаю, вместо `EventTaskAnswer` лучше вставить `Task` и `[]AnswerResult`. Оба типа в пакете `session`.

2023-11-29 11:40 UTC, slowlime commented on internal/session/manager.go
>  }
1. Нельзя лезть в storage в `makeMsg*`. Методы намеренно туда не идут, иначе очень легко получить дедлок. Всё, что нужно для сообщения, требуется передавать через параметры функции.
2. И вообще, если функция хочет в storage лезть, она или `Atomically()` должна вызвать (чего лучше избегать), или `s *UnsafeStorage` принимать. Повторюсь: в `makeMsg*` никакой из этих способов юзать нельзя.
3. В БД лезть тоже нельзя. Это нужно делать снаружи функции, а затем уже передавать в неё результаты.

Сравни, например, с `makeMsgJoined`.

2023-11-29 11:40 UTC, slowlime commented on internal/session/update.go
> +
Если и делать такую функцию, то ресивером должен быть менеджер. В апдейтере этому не место.

2023-11-29 11:40 UTC, slowlime commented on internal/session/update.go
> +		}
Какой штатный сценарий работы бэкэнда может привести к тому, что из списка пропадёт задание? Если нет идей, то надо паниковать (`u.log.Panicf`).

---

И опять прикопаюсь к ошибкам. Когда возвращаем ошибку, надо думать, кому мы её вручаем. Полезна она ему? Нужна ли в таких деталях? Ошибка отражает детали внутренней реализации или же, как и должна, контракт с другими модулями (будь то пакеты или типы)? Создаёт ли она уязвимость?

Применим эти критерии к `ErrTaskDisappeared`:
1. Полезна? Отвечает ли она на вопрос, что нужно предпринять в случае такой ошибки? Нет.
2. Нужна ли в таких деталях? Опустим критерий, так как он имеет смысл только при утвердительном ответе на предыдущий.
3. Это кишки или контракт? Однозначно кишки.
4. Это уязвимость? Клиенту напрямую эти ошибки не отсылаются, поэтому нет.

Два крита провалены, как можно заметить.

2023-11-29 11:40 UTC, slowlime commented on internal/session/update.go
> +			u.changeStateTo(ctx, s, u.makePlainTaskEndedState(s, state))
Предлагаю повесить метод `NeedsPoll() bool` на `Task`. И разруливать переход одним ифом.

2023-11-29 11:40 UTC, slowlime commented on internal/session/update.go
> +		return nil
От метода не ждут, что он вернёт `nil`. Лучше `Panicf`.

2023-11-29 11:40 UTC, slowlime commented on internal/session/update.go
> +		deadline: time.Now().Add(task.GetTaskDuration()), // TODO: calculate task deadline as in docs
Туду про коррекцию времени говорит? Коррекция применяется только при отправке сообщений клиенту. Она же разная для разных клиентов будет. Её (в идеале) должна высчитывать и учитывать только горутина, которая `ServerTx` в жсон транслирует.

2023-11-29 11:40 UTC, slowlime commented on internal/ws/converters/task_end_converters.go
Во многих гайдах к го я читал, что имена надо брать короткие и неизбыточные. (Типа го не жава — название длиной в жизнь некруто.) Хрестоматийный пример — `Reader`, который `io.Reader` и `buf.Reader`. Там же пишут, что название файла должно состоять из одного слова, поэтому вопроса, что юзать для разделения слов (`_` / `-`) в имени файла, возникать не должно в принципе.

Здесь же слов три, и последнее дублирует название пакета.

2023-11-29 11:40 UTC, slowlime commented on internal/ws/converters/task_end_converters.go
> +	for i := 0; i < len(m.Answers); i++ {
Это же через `range` делается.

2023-11-29 13:26 UTC, slowlime requested changes

2023-11-29 13:26 UTC, slowlime commented on internal/session/manager.go
> +// makeMsgTaskStart must be called only when you acquired storage.mu
Неправда. =P

2023-11-29 13:26 UTC, slowlime commented on internal/session/update.go
> +}
Хотелось бы, чтобы в одной функции не смешивалось обращение к БД, расчленение состояния и составление сообщения. Как-то негигиенично получается.

Создавать идшки пикч лучше **при переходе в TaskStartState**. Тогда `state.answers` **уже** должен быть заполнен к моменту старта задания (что, в целом, логично). К этому же подталкивает то, что `TaskStarted` отправляется не только при начале задания, но и при переподключении игрока: генерить ид в последнем случае мы не должны.

В итоге от всей функции останутся 4 ветки на 4 типа заданий. Отвяжем теперь его от стейта. Для этого функция не должна сама выдёргивать `taskIdx`, `answers` и `deadline`.

В конце получим красивую чистую функцию, и её нужно перетащить в менеджер на смену не особо безопасному `makeMsgTaskStart`.

Итого:
1. Сообщение должна создавать функция `(*Manager).makeMsgTaskStart` и **только она**.
2. Функция **не должна** лезть в БД.
3. Функция **не должна** принимать `State` или `*TaskStartedState`.

P. S. Если от плеера нужен только ид, надо брать `PlayerID`, а не всего `Player`. Впрочем, после переделки функции игрок ни в каком виде не потребуется.

2023-11-29 13:26 UTC, slowlime commented on internal/session/update.go
> +		})
Во всём остальном коде это делается через итерацию по `PlayerTxs`.

2023-11-29 13:26 UTC, slowlime commented on internal/session/update.go
> +			u.log.Panicf("unexpected task disappearance ")
Надо б здесь индекс задания писать (имею в виду, как в `invalid task index: %d`). Подобно другим местам.

2023-11-29 13:26 UTC, slowlime commented on internal/session/update.go
> +		})
`PlayerTxs`.

2023-11-29 15:17 UTC, AleksandrMatsko commented on internal/session/update.go
> +}
У меня возникают трудности с разделением `prepareMsgTaskStart`. Я не понимаю, в какой момент я должен сходить в бд за новой инфой для картинок. В случае переподключения игрока мне точно это придётся сделать ещё раз. Ну и от свичей никуда не деться...

2023-11-29 15:18 UTC, AleksandrMatsko commented on internal/session/update.go
> +}
Я вынес работу с бд в отдельный метод менеджера

2023-11-29 16:00 UTC, slowlime commented on internal/session/update.go
> +			u.log.Panicf("unexpected task disappearance %v in session: %s", state.taskIdx, u.sid)
Сессия и так пишется логгером. Он в префикс там кладётся.

2023-11-29 16:01 UTC, slowlime commented on internal/session/update.go
> +}
Смотри. Когда у нас запускается задание, вызывается метод `(*sessionUpdater).changeStateTo()`. Этот метод имеет в себе свич по `nextState`. Вот именно там, когда `nextState` — `*TaskStartedState` с `PhotoTask`, надо:

1. запустить транзакцию
2. пройтись по всем игрокам в сессии
3. для каждого создать по пикче (и забронировать ссылку на неё)
4. закоммитить транзакцию (**одна** транзакция на **всех** игроков, а не как сейчас)
5. при успехе айдишники вставить как ответы игроков
6. при провале поматериться в лог, выслать internal error игрокам, а сессию аварийно завершить

*Что будет делать `makeMsgTaskStart`?* Он **сам** будет содержать свичкейс по таске. Препейр не нужен: `makeMsgTaskStart` без него бесполезен и травмоопасен, что намекает на бессмысленность разделения.

*А откуда ему достать айдишники для пикч?* Их надо передать в метод. Параметром типа `ImageID`.

*Откуда достанем айдишник, чтоб передать в метод?* Эти айдишники лежат в `*TaskStartedState`: поле `answers` типа `[]Answer`.

*Почему они там лежат?* См. пункт пять. Так как `TaskStart` посылается после запуска игры, он точно будет проделан. Разумеется, это если сейчас `PhotoTask`.

*Что передать в параметр, если у нас не `PhotoTask`?* `ImageID` нулябельный. Передать надо нулл.

А вот выносить в отдельный метод менеджера заказ айдишников не нужно. Можно оставить методом апдейтера. Либо не плодить сущностей и заинлайнить. По вкусу.

P. S. Не забудь пикчу сделать read-only, когда фотозадание завершается:

- проходимся по `answers` (**не списку игроков!** они могли уже ливнуть за это время)
- собираем список айдишников

Дальше делаем метод на тягуне, который принимает сразу список айдишников и всем ставит ридонли. (Вообще, batch processing должно дефолтом быть, а у нас на N игроков приходится делать N тормозных SQL-запросов. Не очень оптимально. Но пока это нас не сильно волнует.)

И опять: транзакция, вызов тягуна, коммит, обработка ошибок.

2023-11-29 16:21 UTC, AleksandrMatsko commented on internal/session/update.go
> +}
>P. S. Не забудь пикчу сделать read-only, когда фотозадание завершается:

>проходимся по answers (не списку игроков! они могли уже ливнуть за это время)
собираем список айдишников
Дальше делаем метод на тягуне, который принимает сразу список айдишников и всем ставит ридонли. (Вообще, batch processing должно дефолтом быть, а у нас на N игроков приходится делать N тормозных SQL-запросов. Не очень оптимально. Но пока это нас не сильно волнует.)

А это уже надо делать в PollStart, т.к. именно к этому моменту они должны быть неизменяемы. Ну и ещё кажется придётся владельца поменять на админа, чтобы пикчи мог любой чел загрузить

2023-11-29 16:28 UTC, slowlime commented on internal/session/update.go
> +}
> А это уже надо делать в PollStart, т.к. именно к этому моменту они должны быть неизменяемы

Ну, вообще, задача называется "старт/**завершение** задания". Неизменяемыми они должны именно на момент завершения. Ровно поэтому там вообще про завершение говорится.

Впрочем, работа не волк. Не убежит. Можно и позже сделать.

> Ну и ещё кажется придётся владельца поменять на админа, чтобы пикчи мог любой чел загрузить

Здесь не понял мысль. Пикчи не нужно загружать любому человеку. Загружать должен только тот клиент, для ответа которого пикча была создана. Или имелось в виду скачивание? Доступ к пикчам должны иметь все участники сессии независимо от владельцев этих пикч.

А так... я давно говорил, что никакой аутентификации на пикчах не нужно.

2023-11-29 16:55 UTC, AleksandrMatsko commented on internal/session/update.go
> +}
> Здесь не понял мысль. Пикчи не нужно загружать любому человеку. Загружать должен только тот клиент, для ответа которого пикча была создана. Или имелось в виду скачивание? Доступ к пикчам должны иметь все участники сессии независимо от владельцев этих пикч.

Не совсем верно подобрал слово. Здесь по загрузил имелось в виду получение пикчи клиентом для показа пользователю во время голосования.

2023-11-29 18:57 UTC, slowlime requested changes

2023-11-29 18:57 UTC, slowlime commented on internal/session/update.go
> +				answer = PhotoTaskAnswer(img)
А здесь-то зачем это делать? Пользователь не может быть добавлен во время игры.

2023-11-29 18:57 UTC, slowlime commented on internal/session/manager.go
> +}
Не открывай здесь транзакцию. Принимай её снаружи. У тебя на каждого игрока сейчас по соединению дёргается из пула.

2023-11-29 18:57 UTC, slowlime commented on internal/session/update.go
> +			})
`PlayerTxs`. Как двумя строчками ниже.

2023-11-29 18:57 UTC, slowlime commented on internal/session/update.go
> +				u.log.Printf("failed to create image metadata in session %s for all players", u.sid)
1. Ид сессии уже пишется логгером автоматически. Специально, чтобы не пришлось постоянно везде указывать. Не надо его, пожалуйста, дублировать.
2. Сообщение об ошибке не сильно полезное. Вот представь, что приложение у нас здесь ошибку выдаст. Как будем дебажить? Самое информативное — `err` — бесследно исчезает.

Внутри транзакции ты знаешь, для какого игрока ты не смог создать пикчу. Сделай `fmt.Errorf("could not register an image for player %s (nickname=%q, clientID=%s): %w", p.ID, p.Nickname, p.ClientID, err)` внутри `ForEachPlayer`. И напечатай её здесь: `u.log.Printf("could not create images for task answers: %s", err)`.

2023-11-29 18:57 UTC, slowlime commented on internal/session/update.go
> +			u.log.Panicf("unexpected task disappearance %v in session: %s", state.taskIdx, u.sid)
Не надо дублировать ид сессии.

2023-11-29 18:57 UTC, slowlime commented on internal/session/update.go
> +		u.log.Panicf("unexpected task disappearance %v in session: %s", 0, u.sid)
Не надо дублировать ид сессии. Заодно можно константу в строку формата переставить.

2023-11-30 04:28 UTC, AleksandrMatsko commented on internal/session/update.go
> +			})
мне тут от игрока, кроме tx, нужен ещё id, чтобы достать соответствующий id пикчи

2023-11-30 07:49 UTC, slowlime approved these changes

2023-11-30 07:51 UTC, merged