Implement makeMsg stubs and send protocol messages
Party-Buddy/backend pull request #35
Opened 2023-12-05 16:51 UTC by slowlime

Я что-то совсем забыл про эти сообщения. Сделал обработку всего нового, чего надобавляли к `ServerTx`.

Пока был на месте, переделал обработку ошибок в вебсокетах. Теперь страданий должно требоваться меньше. :pray:

2023-12-05 17:11 UTC, AleksandrMatsko requested changes

2023-12-05 17:11 UTC, AleksandrMatsko commented on internal/schemas/ws/ws_schema.go
> +	Ready []uuid.UUID `json:"ready"`
Согласно протоколу uuid -> u32

2023-12-05 17:18 UTC, slowlime commented on internal/schemas/ws/ws_schema.go
> +	Ready []uuid.UUID `json:"ready"`
Ловко подметил. Пойду писать PR в протокол. ¯\_(ツ)_/¯

2023-12-05 17:23 UTC, AleksandrMatsko commented on internal/schemas/ws/ws_schema.go
> +	Ready []uuid.UUID `json:"ready"`
Тогда не забудь поправить использование playerID в других местах. Я точно помню, что где-то конвертировал `uuid` в `uint32` или в `int32`

2023-12-06 05:01 UTC, AleksandrMatsko approved these changes

2023-12-06 05:01 UTC, merged